version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: yiisoftware/yii2-php:8.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - .:/var/www/html
    ports:
      - '8000:80'
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: einstytucja
      POSTGRES_PASSWORD: einstytucja
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
