version: '3'
services:
  php:
    image: yiisoftware/yii2-php:8.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - .:/var/www/html
    ports:
      - '8000:80'
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: einstytucja
      POSTGRES_PASSWORD: einstytucja
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: einstytucja

  # phppgadmin:
  #   image: dockage/phppgadmin:latest
  #   ports:
  #     - "8002:80"
  #   environment:
  #     PHP_PG_ADMIN_SERVER_HOST: postgres
  #     PHP_PG_ADMIN_SERVER_PORT: 5432
  #     PHP_PG_ADMIN_SERVER_DEFAULT_DB: postgres
  #     PHP_PG_ADMIN_SERVER_USERNAME: einstytucja
  #     PHP_PG_ADMIN_SERVER_PASSWORD: einstytucja
  #   depends_on:
  #     - postgres
